deployment:
  tasks:
  - export DEPLOYMENT_BRANCH=master
  - export NODE_ENV=production
  - /usr/local/bin/npm install
  - /usr/local/bin/npm run build
  - /bin/cp -R dist/* /home/enstedu/dashboard.enst.edu.mx/
