deployment:
  tasks:
    - export DEPLOY_PATH=/home/enstedu/posgrados.enst.edu.mx
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/ng build --configuration production --output-path dist --base-href /