deployment:
  tasks:
  - /usr/local/bin/npm install
  - /usr/local/bin/npm run build
  - /bin/cp -R dist/* /home/enstedu/dashboard.enst.edu.mx/
  - /bin/cp -R .htaccess /home/enstedu/dashboard.enst.edu.mx/
