# .cpanel.yml
---
---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/enstedu/dashboard.enst.edu.mx/src/
    - /opt/cpanel/ea-nodejs18/bin/npm install --production
    - /opt/cpanel/ea-nodejs18/bin/npm run build -- --output-path=dist
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH